name: Changelog Check

on:
  pull_request:
    branches: [ main ]

jobs:
  changelog-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Check if CHANGELOG.md has been updated
      run: |
        if git diff --name-only origin/${{ github.event.pull_request.base.ref }} ${{ github.sha }} | grep -q "CHANGELOG.md"; then
          echo "CHANGELOG.md has been updated. Good job!"
        else
          echo "Error: CHANGELOG.md has not been updated. Please update the changelog."
          exit 1
        fi

